"""empty message

Revision ID: 81e34fe7e4f3
Revises: 3fe7244e3805
Create Date: 2025-06-06 19:38:19.227983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e34fe7e4f3'
down_revision = '3fe7244e3805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
