"""Added Room model

Revision ID: dd66a31064d2
Revises: aa1167de6b29
Create Date: 2025-05-30 15:47:50.052387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd66a31064d2'
down_revision = 'aa1167de6b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=120), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('photos', sa.String(), nullable=False),
                    sa.Column('rules', sa.String(), nullable=True),
                    sa.Column('capacity', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('host_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['host_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
